### PR TITLE
1.0.4 release

### PR DESCRIPTION
**Pull request by melissa**

### CODE REVIEW

**Comment by joshcooper** [comment]
adhoc passed https://jenkins-master-prod-1.delivery.puppetlabs.net/view/modules/view/Core/view/mailalias_core/view/adhoc/job/forge-module_puppetlabs-mailalias_core_intn-sys_nightly-adhoc/4/

**Comment by joshcooper** [comment]
Should we bump the minimum puppet version?

`"version_requirement": ">= 4.7.0 < 7.0.0"`

**Comment by joshcooper** [comment]
@melissa it still says 4.7: https://github.com/puppetlabs/puppetlabs-mailalias_core/blob/master/metadata.json#L78

**Comment by melissa** [comment]
This PR was targeted at the release branch :-D https://github.com/puppetlabs/puppetlabs-mailalias_core/blob/release/metadata.json#L78

**Comment by joshcooper** [comment]
ahhhh yes, doh!

**Pull request merged**
